# Generated by Django 5.2.13 on 2026-05-14 13:23

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='join_code',
            field=models.CharField(default=teams.models.generate_join_code, max_length=20),
        ),
    ]
