# Generated by Django 5.2.13 on 2026-05-15 10:27

import teams.models
from django.conf import settings
from django.db import migrations, models


def deduplicate_team_data(apps, schema_editor):
    Team = apps.get_model("teams", "Team")
    TeamMembership = apps.get_model("teams", "TeamMembership")

    used_codes = set()
    for team in Team.objects.order_by("id"):
        if team.join_code and team.join_code not in used_codes:
            used_codes.add(team.join_code)
            continue

        new_code = teams.models.generate_join_code()
        while new_code in used_codes or Team.objects.filter(
            join_code=new_code
        ).exists():
            new_code = teams.models.generate_join_code()

        team.join_code = new_code
        team.save(update_fields=["join_code"])
        used_codes.add(new_code)

    seen_memberships = set()
    duplicates = []
    for membership in TeamMembership.objects.order_by("id"):
        key = (membership.user_id, membership.team_id)
        if key in seen_memberships:
            duplicates.append(membership.id)
        else:
            seen_memberships.add(key)

    if duplicates:
        TeamMembership.objects.filter(id__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_join_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_team_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='team',
            name='join_code',
            field=models.CharField(
                default=teams.models.generate_join_code,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='unique_team_membership'),
        ),
    ]
